### PR TITLE
Add functionality to allow users provide a separate service account for gcs remote terraform backend

### PR DESCRIPTION
**Pull request by rochana-atapattu**
This pull request primarily focuses on enhancing the Google Cloud Platform (GCP) integration in the `get-target-config` and `lib` packages. The changes introduce two new optional parameters, `gcp_remote_backend_service_account` and `gcp_remote_backend_workload_identity_provider`, to the `run` function in `get-target-config/src/run.ts` and to the `JobConfig` and `TargetGroup` objects in `lib/src/index.ts`. These parameters are then used in `setup/action.yaml` to authenticate with GCP if they are provided.

GCP Integration Enhancements:

* [`get-target-config/src/run.ts`](diffhunk://#diff-b59f20ac6e750e15e4abdcd9c465c5f327da52e809bd7ee42f93b31d026e84fdR98-R99): Added `gcp_remote_backend_service_account` and `gcp_remote_backend_workload_identity_provider` to the list of parameters in the `run` function. These parameters are used to authenticate with GCP. [[1]](diffhunk://#diff-b59f20ac6e750e15e4abdcd9c465c5f327da52e809bd7ee42f93b31d026e84fdR98-R99) [[2]](diffhunk://#diff-b59f20ac6e750e15e4abdcd9c465c5f327da52e809bd7ee42f93b31d026e84fdR142-R143)

* [`lib/src/index.ts`](diffhunk://#diff-4a6bb1aa13b646dff251f71d1cef651ab13d6b1f366ed3a684ebe5f419ef7770R82-R83): Added `gcp_remote_backend_service_account` and `gcp_remote_backend_workload_identity_provider` as optional parameters to the `JobConfig` and `TargetGroup` objects. These parameters are used to authenticate with GCP. [[1]](diffhunk://#diff-4a6bb1aa13b646dff251f71d1cef651ab13d6b1f366ed3a684ebe5f419ef7770R82-R83) [[2]](diffhunk://#diff-4a6bb1aa13b646dff251f71d1cef651ab13d6b1f366ed3a684ebe5f419ef7770R101-R102)

* [`setup/action.yaml`](diffhunk://#diff-b6d267e114ed118850925c30d2eba0d7ef272efd6dc98f9ed1dc0caf3200d894R98-R110): Added a new step to use the `google-github-actions/auth` action with the `gcp_remote_backend_service_account` and `gcp_remote_backend_workload_identity_provider` parameters if they are provided. This step authenticates with GCP and sets the `GOOGLE_BACKEND_CREDENTIALS` environment variable.

this PR is a follow up PR for #1641

### CODE REVIEW

**Comment by suzuki-shunsuke** [comment]
Thank you for recreating the pull request!
I'll test the pull request in my test environment.

**Comment by rochana-atapattu** [comment]
Thank you for the feedback. I'll try out
`- uses: suzuki-shunsuke/tfaction/setup@pr/1643`

**Comment by rochana-atapattu** [comment]
i tried this on my setup, apply and plan workflows are working as expected with the new feature.

**Comment by suzuki-shunsuke** [comment]
Could you check this comment when you have time?

- https://github.com/suzuki-shunsuke/tfaction/issues/1634#issuecomment-2067212147

**Pull request merged**
