### PR TITLE
Allow conftest policy directory to be specified in global config

### LINKED ISSUE #85: Support customizing Conftest Policy path

### PR DESCRIPTION
**Pull request by florianmutter**
Fixes #85

---

The global configuration `conftest_policy_directory` is added.
This is the file path to the conftest policy directory.
The default value is `policy`.

e.g.

tfaction-root.yaml

```yaml
conftest_policy_directory: terraform/policy
```

### CODE REVIEW

**Comment by suzuki-shunsuke** [comment]
Thank you for your contribution!

**Comment by suzuki-shunsuke** [comment]
I updated [CONTRIBUTING.md](https://github.com/suzuki-shunsuke/tfaction/blob/main/CONTRIBUTING.md).

- https://github.com/suzuki-shunsuke/tfaction/pull/1520

Please read it when you have time.

**Comment by suzuki-shunsuke** [comment]
Hmm. If `conftest_policy_directory` is set but the directory isn't found, the action should fail.

**Comment by suzuki-shunsuke** [comment]
I tested this pull request on my private environment and it worked well.

**Comment by suzuki-shunsuke** [comment]
I'll add the document.

- https://github.com/suzuki-shunsuke/tfaction-docs/pull/209

**Comment by suzuki-shunsuke** [comment]
@florianmutter Thank you for your contribution.
We released the pre-release version v1.1.0-1.
https://github.com/suzuki-shunsuke/tfaction/releases/tag/v1.1.0-1

Could you try this?
If there is no problem, we'll release v1.1.0.

**Comment by florianmutter** [comment]
It does work for us as expected. Thanks you very much!

**Comment by suzuki-shunsuke** [comment]
Thank you confirming it.
We'll release v1.1.0 on Monday.

**Comment by suzuki-shunsuke** [comment]
v1.1.0 is out 🎉
https://github.com/suzuki-shunsuke/tfaction/releases/tag/v1.1.0

**Pull request merged**
