### PR TITLE
fix: added header for `terraform validate` comment

### PR DESCRIPTION
**Pull request by ponkio-o**
Hi, @suzuki-shunsuke 

I added header for `terraform validate` comment.

before
image

after
image

refer to tfmigrate template
https://github.com/suzuki-shunsuke/tfaction/blob/main/tfmigrate-plan/github-comment.yaml

### CODE REVIEW

**Comment by suzuki-shunsuke** [comment]
Thank you for your contribution!

**Review by suzuki-shunsuke — CHANGES_REQUESTED** [review]
Please add a new entry to `github-comment.yaml`'s exec for `terraform validate`.
And specify the key.

https://github.com/suzuki-shunsuke/tfaction/blob/b843b5757af218cd81c2a1d40c02d684b814046d/test/action.yaml#L20C2-L23

**Comment by suzuki-shunsuke** [comment]
And please resolve the conflict.

**Comment by ponkio-o** [comment]
Thank you for your suggestion!
I added template key for `terraform validate` on below commit.
https://github.com/suzuki-shunsuke/tfaction/pull/986/commits/703a3bd11930a44a2e0d04f70adb248e2471ae30

**Review by suzuki-shunsuke — CHANGES_REQUESTED** [review]
Please keep the default template and add a new template.

**Comment by ponkio-o** [comment]
> Please keep the default template and add a new template.

Oops, sorry. I will fix it.

**Comment by suzuki-shunsuke** [comment]
And please fix the indent of YAML.

**Review by suzuki-shunsuke — APPROVED** [review]

**Comment by suzuki-shunsuke** [comment]
Thanks!

**Comment by suzuki-shunsuke** [comment]
v0.6.1 is out 🚀
https://github.com/suzuki-shunsuke/tfaction/releases/tag/v0.6.1

**Pull request merged**
